[workspace]
resolver = "2"
members = [
    "crates/engine_assets", 
    "crates/engine_audio", 
    "crates/engine_core", 
    "crates/engine_ecs", 
    "crates/engine_physics",
    "crates/engine_renderer", 
    "crates/engine_scripting",  
    "crates/engine_window",
    "src"
]

[workspace.dependencies]
engine_window = { path = "crates/engine_window" }

env_logger = "0.11.10"
game-loop = "1.3.0"
gilrs = "0.11.1"
raw-window-handle = "0.6.2"
winit = "0.30.13"
winit-input-map = "0.6.1"

